# Generated by Django 3.0.5 on 2020-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orfol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategories',
            field=models.CharField(choices=[('Found', 'Found'), ('Lost', 'Lost')], default='L', max_length=50),
        ),
    ]
