# Generated by Django 3.0.5 on 2020-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orfol', '0004_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
