# Generated by Django 3.0.5 on 2020-04-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orfol', '0009_auto_20200423_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
