# Generated by Django 3.0.5 on 2020-05-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orfol', '0002_auto_20200517_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('L', 'Lost'), ('F', 'Found')], default='L', max_length=80),
        ),
    ]
