# Generated by Django 3.0.5 on 2020-05-22 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orfol', '0005_auto_20200518_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_occurrence',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
