# Generated by Django 3.0.5 on 2020-04-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Accessories', 'Accessories'), ('Books', 'Books'), ('clothing', 'Female'), ('computing', 'computing'), ('Documents', 'Documents'), ('humans', 'humans'), ('Keys', 'Keys'), ('machinary', 'machinary'), ('money', 'money'), ('mobile', 'mobile'), ('sports', 'sports')], default='E', max_length=50)),
                ('icon', models.ImageField(default='default.jpg', upload_to='Categories_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategories', models.CharField(choices=[('F', 'Found'), ('L', 'Lost')], default='L', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('subcity', models.CharField(max_length=80)),
                ('image', models.ImageField(default='default.jpg', upload_to='report_pics')),
                ('reward', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orfol.Category')),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orfol.Subcategory')),
            ],
        ),
    ]
