# Generated by Django 3.0.5 on 2020-04-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orfol', '0005_auto_20200423_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
