# Generated by Django 3.0.5 on 2020-04-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orfol', '0008_auto_20200423_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
