# Generated by Django 3.0.5 on 2020-04-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orfol', '0015_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='username',
        ),
    ]
