# Generated by Django 3.0.5 on 2020-04-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orfol', '0018_auto_20200424_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='username',
        ),
    ]
